inherit_from: config/style.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-vicenzo
  - rubocop-internal_affairs

InternalAffairs/UndefinedConfig: # False positive because conflicts with Rubocop Layout namespace
  Exclude:
    - 'lib/rubocop/cop/vicenzo/layout/**/*'

Naming/FileName:
  Exclude:
    - lib/rubocop-vicenzo.rb

RSpec/ExampleLength:
  Enabled: false

Vicenzo/RSpec/LeakyDefinition:
  Exclude:
    - 'spec/support/**/*'
    - 'spec/rubocop/cop/vicenzo/rspec/leaky_definition_spec.rb'
