plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-vicenzo
  - rubocop-internal_affairs

AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-vicenzo.rb

RSpec/ContextWording:
  Prefixes:
    - and
    - but
    - when
    - with
    - without

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
