plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-vicenzo
  - rubocop-internal_affairs

AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-vicenzo.rb

RSpec/ExampleLength:
  Enabled: false
