plugins:
  - rubocop-internal_affairs
  - rubocop-rspec
  - rubocop-vicenzo

AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - lib/rubocop-vicenzo.rb

RSpec/ExampleLength:
  Enabled: false
